### ISSUE TITLE
Version in `_version.py` incorrect

### ISSUE THREAD

**Issue by ThomasBur** [python-visualization/branca#165] opened 2024-04-05 05:22 UTC
G'day, looks like there's an issue with the version being generated by `setuptools` when installing from the git repository.

It's creating versions starting with 0.1 instead of 0.7.

This makes it a lot harder to test its interaction with other libraries, as `folium` requires version `0.3.0` or higher.

When I was mistakenly using an outdated version of `setuptools`, I also got the message recommending:
migrating from the deprecated setup_requires mechanism to pep517/518
and using a pyproject.toml to declare build dependencies
which are reliably pre-installed before running the build tools

**Comment by Conengmo** [comment] 2024-04-05 06:45
Probably related to https://github.com/python-visualization/folium/pull/1922 as well.

**Comment by Conengmo** [comment] 2024-04-05 07:26
I can't reproduce this issue. 

First I upgrade the packages from requirements.txt and requirements-dev.txt. Then I install Branca from git:

```
pip install git+https://github.com/python-visualization/branca.git
```

I get `Successfully installed branca-0.7.2.dev6+g90579e9`.

```
>>> import branca
>>> branca.__version__
'0.7.2.dev6+g90579e9'
>>> branca._version.__version__
'0.7.2.dev6+g90579e9'
```

**Comment by Conengmo** [comment] 2024-04-05 07:27
I was investigating something similar in https://github.com/python-visualization/folium/pull/1922, there the issue was that the full commit history was not being fetched. In what environment are you having this issue?

**Comment by Conengmo** [comment] 2024-05-06 17:23
@ThomasBur any news on this one, or is it okay to close?

**Comment by Conengmo** [comment] 2024-05-18 07:42
I'll close this issue since I hope the issue was with the full commit history, not with something with Branca.

**Closed by Conengmo** 2024-05-18 07:42 UTC
